// Fichier généré par tool/generer_textes.mjs depuis sahla/serveur/public/textes.js : ne pas modifier à la main.
// À faire relire par des locuteurs natifs : hassaniya (mey), pulaar (ff), wolof (wo).
// Soninké (snk) : salutation seulement, le reste en français en attendant une traduction validée.

import 'mascotte/poses.dart';

class SahlaTextes {
  const SahlaTextes({
    required this.nom,
    required this.sousTitre,
    required this.titre,
    required this.intro,
    required this.saisie,
    required this.envoyer,
    required this.nouvelle,
    required this.suggestions,
    required this.poses,
    required this.erreurs,
  });

  final String nom;
  final String sousTitre;
  final String titre;
  final String intro;
  final String saisie;
  final String envoyer;
  final String nouvelle;
  final List<String> suggestions;
  final Map<SahlaPose, String> poses;
  final Map<String, String> erreurs;

  String erreur(String code) => erreurs[code] ?? erreurs['indisponible']!;

  /// Textes pour un code de langue (fr, ar, mey, ff, snk, wo, en, es, pt, zh), français par défaut.
  static SahlaTextes pour(String langue) => sahlaTextes[langue] ?? sahlaTextes['fr']!;

  static bool droiteAGauche(String langue) => const {'ar', 'mey'}.contains(langue);
}

const sahlaTextes = <String, SahlaTextes>{
  'fr': SahlaTextes(
    nom: 'Français',
    sousTitre: 'Assistante Sehelli',
    titre: 'Bonjour, je suis Sahla !',
    intro: 'Je peux estimer une course, suivre une commande, vérifier votre solde ou contacter le support.',
    saisie: 'Écrivez votre message…',
    envoyer: 'Envoyer',
    nouvelle: 'Nouvelle conversation',
    suggestions: [
      'Combien pour aller à l\'aéroport ?',
      'Où est mon chauffeur ?',
      'Quel est mon solde ?',
      'J\'ai oublié un sac dans un taxi',
    ],
    poses: {
      SahlaPose.hello: 'Bonjour !',
      SahlaPose.go: 'En route',
      SahlaPose.search: 'Je cherche…',
      SahlaPose.bravo: 'Bravo !',
      SahlaPose.oops: 'Oups…',
      SahlaPose.empty: 'Rien ici',
    },
    erreurs: {
      'reseau': 'Oups… la connexion a échoué. Réessayez.',
      'limite': 'Vous envoyez beaucoup de messages. Patientez une minute.',
      'refus': 'Je ne peux pas vous aider pour cette demande.',
      'occupe': 'Je réponds encore au message précédent.',
      'trop_long': 'Votre message est trop long. Pouvez-vous le raccourcir ?',
      'indisponible': 'Je suis indisponible pour le moment. Réessayez dans un instant.',
      'surcharge': 'Beaucoup de demandes en ce moment. Réessayez dans un instant.',
      'non_connecte': 'Connectez-vous à votre compte Sehelli pour discuter avec Sahla.',
    },
  ),
  'ar': SahlaTextes(
    nom: 'العربية',
    sousTitre: 'مساعدة سهّلي',
    titre: 'مرحبًا، أنا سهلة!',
    intro: 'يمكنني تقدير سعر رحلة، وتتبع طلبك، والتحقق من رصيدك، أو التواصل مع الدعم.',
    saisie: 'اكتب رسالتك…',
    envoyer: 'إرسال',
    nouvelle: 'محادثة جديدة',
    suggestions: [
      'كم سعر الرحلة إلى المطار؟',
      'أين السائق؟',
      'كم رصيدي؟',
      'نسيت حقيبة في سيارة أجرة',
    ],
    poses: {
      SahlaPose.hello: 'مرحبًا!',
      SahlaPose.go: 'في الطريق',
      SahlaPose.search: 'أبحث…',
      SahlaPose.bravo: 'أحسنت!',
      SahlaPose.oops: 'عذرًا…',
      SahlaPose.empty: 'لا شيء هنا',
    },
    erreurs: {
      'reseau': 'عذرًا، فشل الاتصال. حاول مرة أخرى.',
      'limite': 'أرسلت رسائل كثيرة. انتظر دقيقة من فضلك.',
      'refus': 'لا يمكنني المساعدة في هذا الطلب.',
      'occupe': 'ما زلت أجيب على الرسالة السابقة.',
      'trop_long': 'رسالتك طويلة جدًا. هل يمكنك اختصارها؟',
      'indisponible': 'الخدمة غير متاحة حاليًا. حاول بعد قليل.',
      'surcharge': 'هناك طلبات كثيرة الآن. حاول بعد قليل.',
      'non_connecte': 'سجّل الدخول إلى حسابك في سهّلي للتحدث مع سهلة.',
    },
  ),
  'mey': SahlaTextes(
    nom: 'الحسانية',
    sousTitre: 'مساعدة سهّلي',
    titre: 'السلام عليكم، آن سهلة!',
    intro: 'نگد نحسب لك سومة المشوار، نتبع طلبيتك، نشوف رصيدك، ولا نوصلك بالدعم.',
    saisie: 'اكتب رسالتك…',
    envoyer: 'رسّل',
    nouvelle: 'محادثة جديدة',
    suggestions: [
      'ش سومة المشوار للمطار؟',
      'الشيفور فين؟',
      'شحال عندي في المحفظة؟',
      'نسيت شنطة في التاكسي',
    ],
    poses: {
      SahlaPose.hello: 'السلام!',
      SahlaPose.go: 'في الطريق',
      SahlaPose.search: 'نفتش…',
      SahlaPose.bravo: 'مبروك!',
      SahlaPose.oops: 'اسمح لي…',
      SahlaPose.empty: 'ما كاين شي',
    },
    erreurs: {
      'reseau': 'اسمح لي، الاتصال ما زين. عاود.',
      'limite': 'رسلت رسائل ياسر. صبر دقيقة.',
      'refus': 'ما نگد نعاونك في هذا.',
      'occupe': 'مازلت نجاوب على الرسالة اللي قبل.',
      'trop_long': 'الرسالة طويلة ياسر. قصّرها.',
      'indisponible': 'الخدمة ما هي متوفرة دروك. عاود من بعد شوي.',
      'surcharge': 'الطلبات ياسر دروك. عاود من بعد شوي.',
      'non_connecte': 'ادخل لحسابك في سهّلي باش تتكلم مع سهلة.',
    },
  ),
  'ff': SahlaTextes(
    nom: 'Pulaar',
    sousTitre: 'Ballotooɗo Sehelli',
    titre: 'Jam waali, ko min woni Sahla!',
    intro: 'Mbaawmi wallude ma e taksi, colis, e portefeuille Sehelli maa.',
    saisie: 'Winndu mesaas maa…',
    envoyer: 'Neldu',
    nouvelle: 'Yeewtere hesere',
    suggestions: [
      'Taksi to aeropoor ko jelu?',
      'Hol to dognoowo am woni?',
      'Ceede njelu ngondi e portefeuille am?',
      'Mi yejjitii saak e nder taksi',
    ],
    poses: {
      SahlaPose.hello: 'Jam waali!',
      SahlaPose.go: 'E laawol',
      SahlaPose.search: 'Mi yiylotoo…',
      SahlaPose.bravo: 'Bravo!',
      SahlaPose.oops: 'Yaafo…',
      SahlaPose.empty: 'Alaa hay huunde',
    },
    erreurs: {
      'reseau': 'Yaafo, jokkondiral ngal waawaani. Fuɗɗito.',
      'limite': 'A neldii mesaasji keewɗi. Muñ hojomaare.',
      'refus': 'Mi waawaa wallude ma e ndee ɗaɓɓaande.',
      'occupe': 'Mi jaabotoo mesaas gadano oo tawo.',
      'trop_long': 'Mesaas oo juutii. Winndu ko raɓɓiɗi.',
      'indisponible': 'Mi heɓaaka jooni. Fuɗɗito seeɗa.',
      'surcharge': 'Ɗaɓɓaaɗe keewii jooni. Fuɗɗito seeɗa.',
      'non_connecte': 'Naatu e konte Sehelli maa ngam haalde e Sahla.',
    },
  ),
  'snk': SahlaTextes(
    nom: 'Soninkanxaane',
    sousTitre: 'Assistante Sehelli',
    titre: 'An moxo ? Je suis Sahla !',
    intro: 'Je peux estimer une course, suivre une commande, vérifier votre solde ou contacter le support.',
    saisie: 'Écrivez votre message…',
    envoyer: 'Envoyer',
    nouvelle: 'Nouvelle conversation',
    suggestions: [
      'Combien pour aller à l\'aéroport ?',
      'Où est mon chauffeur ?',
      'Quel est mon solde ?',
      'J\'ai oublié un sac dans un taxi',
    ],
    poses: {
      SahlaPose.hello: 'Bonjour !',
      SahlaPose.go: 'En route',
      SahlaPose.search: 'Je cherche…',
      SahlaPose.bravo: 'Bravo !',
      SahlaPose.oops: 'Oups…',
      SahlaPose.empty: 'Rien ici',
    },
    erreurs: {
      'reseau': 'Oups… la connexion a échoué. Réessayez.',
      'limite': 'Vous envoyez beaucoup de messages. Patientez une minute.',
      'refus': 'Je ne peux pas vous aider pour cette demande.',
      'occupe': 'Je réponds encore au message précédent.',
      'trop_long': 'Votre message est trop long. Pouvez-vous le raccourcir ?',
      'indisponible': 'Je suis indisponible pour le moment. Réessayez dans un instant.',
      'surcharge': 'Beaucoup de demandes en ce moment. Réessayez dans un instant.',
      'non_connecte': 'Connectez-vous à votre compte Sehelli pour discuter avec Sahla.',
    },
  ),
  'wo': SahlaTextes(
    nom: 'Wolof',
    sousTitre: 'Ndimbalukat bu Sehelli',
    titre: 'Salaam aleekum, maa ngi tudd Sahla!',
    intro: 'Mën naa la dimbali ci taksi, colis ak sa kalpe Sehelli.',
    saisie: 'Bindal sa bataaxal…',
    envoyer: 'Yónnee',
    nouvelle: 'Waxtaan bu bees',
    suggestions: [
      'Ñaata la taksi ba aéroport?',
      'Fan la sama dawalkat nekk?',
      'Ñaata laa am ci sama kalpe?',
      'Fàtte naa sama sàkk ci taksi',
    ],
    poses: {
      SahlaPose.hello: 'Salaam!',
      SahlaPose.go: 'Ci yoon wi',
      SahlaPose.search: 'Maa ngi seet…',
      SahlaPose.bravo: 'Bravo!',
      SahlaPose.oops: 'Baal ma…',
      SahlaPose.empty: 'Dara amul',
    },
    erreurs: {
      'reseau': 'Baal ma, connexion bi baaxul. Jéemaatal.',
      'limite': 'Yónnee nga bataaxal yu bari. Muñal benn minit.',
      'refus': 'Mënuma la dimbali ci laaj bii.',
      'occupe': 'Maa ngi tontu bataaxal bi jiitu.',
      'trop_long': 'Bataaxal bi dafa gudd. Gàttal ko.',
      'indisponible': 'Mënuma tontu léegi. Jéemaatal tuuti ci kanam.',
      'surcharge': 'Laaj yi bari nañu léegi. Jéemaatal tuuti ci kanam.',
      'non_connecte': 'Duggal ci sa kont Sehelli ngir waxtaan ak Sahla.',
    },
  ),
  'en': SahlaTextes(
    nom: 'English',
    sousTitre: 'Sehelli assistant',
    titre: 'Hi, I\'m Sahla!',
    intro: 'I can estimate a ride, track an order, check your balance or contact support.',
    saisie: 'Type your message…',
    envoyer: 'Send',
    nouvelle: 'New conversation',
    suggestions: [
      'How much to the airport?',
      'Where is my driver?',
      'What\'s my balance?',
      'I left a bag in a taxi',
    ],
    poses: {
      SahlaPose.hello: 'Hello!',
      SahlaPose.go: 'On the way',
      SahlaPose.search: 'Looking…',
      SahlaPose.bravo: 'Well done!',
      SahlaPose.oops: 'Oops…',
      SahlaPose.empty: 'Nothing here',
    },
    erreurs: {
      'reseau': 'Oops… the connection failed. Please try again.',
      'limite': 'You\'re sending a lot of messages. Please wait a minute.',
      'refus': 'I can\'t help with this request.',
      'occupe': 'I\'m still answering your previous message.',
      'trop_long': 'Your message is too long. Could you shorten it?',
      'indisponible': 'I\'m unavailable right now. Please try again shortly.',
      'surcharge': 'Lots of requests right now. Please try again shortly.',
      'non_connecte': 'Sign in to your Sehelli account to chat with Sahla.',
    },
  ),
  'es': SahlaTextes(
    nom: 'Español',
    sousTitre: 'Asistente de Sehelli',
    titre: '¡Hola, soy Sahla!',
    intro: 'Puedo estimar un viaje, seguir un pedido, consultar su saldo o contactar con soporte.',
    saisie: 'Escriba su mensaje…',
    envoyer: 'Enviar',
    nouvelle: 'Nueva conversación',
    suggestions: [
      '¿Cuánto cuesta ir al aeropuerto?',
      '¿Dónde está mi conductor?',
      '¿Cuál es mi saldo?',
      'Olvidé una bolsa en un taxi',
    ],
    poses: {
      SahlaPose.hello: '¡Hola!',
      SahlaPose.go: 'En camino',
      SahlaPose.search: 'Buscando…',
      SahlaPose.bravo: '¡Bravo!',
      SahlaPose.oops: 'Uy…',
      SahlaPose.empty: 'Nada por aquí',
    },
    erreurs: {
      'reseau': 'Uy… falló la conexión. Inténtelo de nuevo.',
      'limite': 'Está enviando muchos mensajes. Espere un minuto.',
      'refus': 'No puedo ayudarle con esta solicitud.',
      'occupe': 'Todavía estoy respondiendo a su mensaje anterior.',
      'trop_long': 'Su mensaje es demasiado largo. ¿Puede acortarlo?',
      'indisponible': 'No estoy disponible ahora. Inténtelo en un momento.',
      'surcharge': 'Hay muchas solicitudes ahora. Inténtelo en un momento.',
      'non_connecte': 'Inicie sesión en su cuenta de Sehelli para hablar con Sahla.',
    },
  ),
  'pt': SahlaTextes(
    nom: 'Português',
    sousTitre: 'Assistente da Sehelli',
    titre: 'Olá, eu sou a Sahla!',
    intro: 'Posso estimar uma corrida, acompanhar um pedido, verificar o seu saldo ou contactar o suporte.',
    saisie: 'Escreva a sua mensagem…',
    envoyer: 'Enviar',
    nouvelle: 'Nova conversa',
    suggestions: [
      'Quanto custa ir ao aeroporto?',
      'Onde está o meu motorista?',
      'Qual é o meu saldo?',
      'Esqueci uma mala num táxi',
    ],
    poses: {
      SahlaPose.hello: 'Olá!',
      SahlaPose.go: 'A caminho',
      SahlaPose.search: 'A procurar…',
      SahlaPose.bravo: 'Boa!',
      SahlaPose.oops: 'Ups…',
      SahlaPose.empty: 'Nada aqui',
    },
    erreurs: {
      'reseau': 'Ups… a ligação falhou. Tente novamente.',
      'limite': 'Está a enviar muitas mensagens. Aguarde um minuto.',
      'refus': 'Não posso ajudar com este pedido.',
      'occupe': 'Ainda estou a responder à mensagem anterior.',
      'trop_long': 'A sua mensagem é demasiado longa. Pode encurtá-la?',
      'indisponible': 'Estou indisponível de momento. Tente daqui a pouco.',
      'surcharge': 'Muitos pedidos neste momento. Tente daqui a pouco.',
      'non_connecte': 'Inicie sessão na sua conta Sehelli para falar com a Sahla.',
    },
  ),
  'zh': SahlaTextes(
    nom: '中文',
    sousTitre: 'Sehelli 智能助手',
    titre: '您好，我是 Sahla！',
    intro: '我可以为您估算车费、跟踪订单、查询余额或联系客服。',
    saisie: '输入消息…',
    envoyer: '发送',
    nouvelle: '新对话',
    suggestions: [
      '去机场多少钱？',
      '我的司机在哪里？',
      '我的余额是多少？',
      '我把包落在出租车上了',
    ],
    poses: {
      SahlaPose.hello: '您好！',
      SahlaPose.go: '在路上',
      SahlaPose.search: '正在查找…',
      SahlaPose.bravo: '太棒了！',
      SahlaPose.oops: '哎呀…',
      SahlaPose.empty: '这里什么都没有',
    },
    erreurs: {
      'reseau': '哎呀，连接失败。请重试。',
      'limite': '您发送的消息太多了，请稍等一分钟。',
      'refus': '抱歉，我无法处理这个请求。',
      'occupe': '我还在回复您的上一条消息。',
      'trop_long': '消息太长了，可以缩短一些吗？',
      'indisponible': '暂时无法服务，请稍后再试。',
      'surcharge': '当前请求较多，请稍后再试。',
      'non_connecte': '请登录您的 Sehelli 账户，与 Sahla 对话。',
    },
  ),
};
